-- ResqNet Supabase Schema
-- Run this in your Supabase SQL Editor

-- 1. Enable RLS
-- (Already enabled by default in most cases, but good practice)

-- 2. Create Teams Table
CREATE TABLE IF NOT EXISTS public.teams (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    leader TEXT NOT NULL,
    members INTEGER DEFAULT 0,
    vehicle TEXT,
    zone TEXT,
    status TEXT CHECK (status IN ('En Route', 'On Site', 'Returning', 'Standby')),
    pin_x FLOAT NOT NULL,
    pin_y FLOAT NOT NULL,
    color TEXT CHECK (color IN ('red', 'blue', 'green')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Incidents Table
CREATE TABLE IF NOT EXISTS public.incidents (
    id TEXT PRIMARY KEY,
    location TEXT NOT NULL,
    type TEXT NOT NULL,
    team TEXT REFERENCES public.teams(name) ON DELETE SET NULL,
    status TEXT CHECK (status IN ('Open', 'In Progress', 'Resolved')),
    time_ago TEXT,
    response_min INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    driver TEXT,
    location TEXT,
    fuel INTEGER DEFAULT 100,
    status TEXT CHECK (status IN ('Active', 'Idle', 'Maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Alerts Table
CREATE TABLE IF NOT EXISTS public.alerts (
    id TEXT PRIMARY KEY,
    severity TEXT CHECK (severity IN ('critical', 'warning', 'info')),
    title TEXT NOT NULL,
    description TEXT,
    location TEXT,
    time_ago TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Field Updates Table
CREATE TABLE IF NOT EXISTS public.field_updates (
    id TEXT PRIMARY KEY,
    time TEXT NOT NULL,
    unit TEXT,
    message TEXT NOT NULL,
    kind TEXT CHECK (kind IN ('urgent', 'update', 'success')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Supplies Table
CREATE TABLE IF NOT EXISTS public.supplies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone TEXT NOT NULL,
    food INTEGER DEFAULT 0,
    water INTEGER DEFAULT 0,
    medical INTEGER DEFAULT 0,
    blankets INTEGER DEFAULT 0,
    status TEXT CHECK (status IN ('Sufficient', 'Low', 'Critical')),
    coverage INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Seed Data
INSERT INTO public.teams (id, name, leader, members, vehicle, zone, status, pin_x, pin_y, color) VALUES
('T-01', 'Alpha Squad', 'Capt. R. Mehta', 8, 'Rescue Van', 'Zone A (Dharavi)', 'On Site', 22, 38, 'red'),
('T-02', 'Bravo Unit', 'Lt. S. Khan', 6, 'Ambulance', 'Zone B (Kurla)', 'En Route', 40, 55, 'blue'),
('T-03', 'Delta Force', 'Capt. A. Nair', 10, 'Fire Truck', 'Zone C (Andheri)', 'On Site', 58, 30, 'red'),
('T-04', 'Eagle Team', 'Lt. P. Verma', 5, 'Helicopter', 'Zone D (Thane)', 'Returning', 75, 22, 'green'),
('T-05', 'Falcon Squad', 'Capt. M. Iyer', 7, 'Boat', 'Zone E (Borivali)', 'En Route', 30, 70, 'blue'),
('T-06', 'Griffin Unit', 'Lt. D. Rao', 9, 'Rescue Van', 'Zone B (Kurla)', 'Standby', 65, 65, 'green')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.incidents (id, location, type, team, status, time_ago, response_min) VALUES
('INC-1043', 'Dharavi - Sector 4', 'Flood', 'Alpha Squad', 'In Progress', '12 min ago', 8),
('INC-1042', 'Andheri West', 'Building Collapse', 'Delta Force', 'Open', '27 min ago', 11),
('INC-1041', 'Kurla East', 'Medical Emergency', 'Bravo Unit', 'In Progress', '44 min ago', 6),
('INC-1040', 'Thane Junction', 'Road Block', 'Eagle Team', 'Resolved', '1 hr ago', 14)
ON CONFLICT (id) DO NOTHING;

-- Add RLS Policies (Allow all authenticated users to read)
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read" ON public.teams FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.incidents FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.vehicles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.alerts FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.field_updates FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated read" ON public.supplies FOR SELECT TO authenticated USING (true);
